name:  "投稿模板"
title: "投稿标题"
description: "摸鱼周刊投稿模板"
body:
  - type: markdown
    attributes:
      value: 
        请修改投稿标题，在右侧选择对应的label
  - type: textarea
    id: description
    attributes:
      label: 描述
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: 链接
      placeholder: eg. https://www.github.com
    validations:
      required: true
  - type: input
    id: keyword
    attributes:
      label: 关键词
      placeholder: eg. Vue React
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: 其他
    validations:
      required: false
